# Generated by Django 4.0.6 on 2022-09-26 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionId', models.CharField(max_length=20)),
                ('sectionName', models.CharField(max_length=50)),
                ('numberOfEmployees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.CharField(max_length=20)),
                ('empName', models.CharField(max_length=50)),
                ('departmentId', models.CharField(max_length=20)),
                ('empDesignation', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('bloodGroup', models.CharField(max_length=10)),
                ('addressLine1', models.CharField(max_length=100)),
                ('addressLine2', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('createdOn', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 7, 59, 24, 897119))),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=20)),
                ('studentName', models.CharField(max_length=50)),
                ('departmentId', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('bloodGroup', models.CharField(max_length=10)),
                ('addressLine1', models.CharField(max_length=100)),
                ('addressLine2', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('marks', models.CharField(max_length=15)),
                ('createdOn', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 7, 59, 24, 898115))),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
