# Generated by Django 4.0.6 on 2022-09-26 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentId', models.CharField(max_length=15)),
                ('departmentName', models.CharField(max_length=50)),
                ('intake', models.IntegerField()),
                ('createdOn', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 7, 59, 24, 862233))),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyId', models.CharField(max_length=15)),
                ('facultyName', models.CharField(max_length=50)),
                ('createdOn', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 7, 59, 24, 863211))),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labId', models.CharField(max_length=15)),
                ('labName', models.CharField(max_length=50)),
                ('labInCharge', models.CharField(max_length=50)),
                ('createdOn', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 7, 59, 24, 864206))),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=15)),
                ('StudentName', models.CharField(max_length=50)),
                ('createdOn', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 7, 59, 24, 863211))),
            ],
        ),
    ]
